/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import conexionBD.Conexion;

/**
 *
 * @author LUIS LEITON
 */
public class Principal extends javax.swing.JFrame{

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIrRegistroEscuela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnIrRegistroCurso = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnIrRegistroCoYRequisitos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnIrCrearPlan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnIrConsultarPlan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnIrConsultarPlanConCurso = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnIrConsultarRequisitos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnIrConsultarCorrequisitos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnIrEliminarRequisito = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnIrEliminarCursoPlan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnIrEliminarCurso = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO AL GESTOR DE PLANES DE ESTUDIO");

        btnIrRegistroEscuela.setText("Registrar");
        btnIrRegistroEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrRegistroEscuelaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Registro de Escuela o Área Académica");

        btnIrRegistroCurso.setText("Registrar");
        btnIrRegistroCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrRegistroCursoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Registro de un curso");

        btnIrRegistroCoYRequisitos.setText("Registrar");
        btnIrRegistroCoYRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrRegistroCoYRequisitosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Registro de requisitos y correquisitos a un curso");

        btnIrCrearPlan.setText("Crear");
        btnIrCrearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrCrearPlanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Crear un plan de estudios");

        btnIrConsultarPlan.setText("Consultar");
        btnIrConsultarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrConsultarPlanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Consultar plan de estudios");

        btnIrConsultarPlanConCurso.setText("Consultar");
        btnIrConsultarPlanConCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrConsultarPlanConCursoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Consultar plan de estudios con un curso particular");

        btnIrConsultarRequisitos.setText("Consultar");
        btnIrConsultarRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrConsultarRequisitosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Consultar requisitos de un curso");

        btnIrConsultarCorrequisitos.setText("Consultar");
        btnIrConsultarCorrequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrConsultarCorrequisitosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Consultar correquisitos de un curso");

        btnIrEliminarRequisito.setText("Eliminar");
        btnIrEliminarRequisito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrEliminarRequisitoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Eliminar un requisito de un curso");

        btnIrEliminarCursoPlan.setText("Eliminar");
        btnIrEliminarCursoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrEliminarCursoPlanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Eliminar un curso del plan de estudios");

        btnIrEliminarCurso.setText("Eliminar");
        btnIrEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrEliminarCursoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Eliminar un curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIrConsultarRequisitos))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIrConsultarPlanConCurso))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnIrRegistroCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnIrRegistroEscuela, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnIrRegistroCoYRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnIrCrearPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnIrConsultarPlan, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIrConsultarCorrequisitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIrEliminarRequisito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIrEliminarCursoPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIrEliminarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIrRegistroEscuela)
                        .addGap(18, 18, 18)
                        .addComponent(btnIrRegistroCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btnIrRegistroCoYRequisitos)
                        .addGap(18, 18, 18)
                        .addComponent(btnIrCrearPlan)
                        .addGap(18, 18, 18)
                        .addComponent(btnIrConsultarPlan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIrConsultarPlanConCurso)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnIrConsultarRequisitos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(btnIrConsultarCorrequisitos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(btnIrEliminarRequisito))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(btnIrEliminarCursoPlan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(btnIrEliminarCurso))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrRegistroEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrRegistroEscuelaActionPerformed

      RegistroEscuela RE = new RegistroEscuela();
      RE.setVisible(true);
      
      this.dispose();  
    }//GEN-LAST:event_btnIrRegistroEscuelaActionPerformed

    private void btnIrRegistroCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrRegistroCursoActionPerformed
      RegistroCursos RC = new RegistroCursos();
      RC.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_btnIrRegistroCursoActionPerformed

    private void btnIrRegistroCoYRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrRegistroCoYRequisitosActionPerformed
      RegistroCoYRequisitos RCR = new RegistroCoYRequisitos();
      RCR.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_btnIrRegistroCoYRequisitosActionPerformed

    private void btnIrCrearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrCrearPlanActionPerformed
      RegistroPlanEstudio RPE = new RegistroPlanEstudio();
      RPE.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_btnIrCrearPlanActionPerformed

    private void btnIrConsultarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConsultarPlanActionPerformed
      ConsultarPlanEstudio CPE = new ConsultarPlanEstudio();
      CPE.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_btnIrConsultarPlanActionPerformed

    private void btnIrConsultarPlanConCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConsultarPlanConCursoActionPerformed
      ConsultarCursoPlanEstudio CEPE = new ConsultarCursoPlanEstudio();
      CEPE.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnIrConsultarPlanConCursoActionPerformed

    private void btnIrConsultarRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConsultarRequisitosActionPerformed
      ConsultarRequisitosCurso CRC = new ConsultarRequisitosCurso();
      CRC.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnIrConsultarRequisitosActionPerformed

    private void btnIrConsultarCorrequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConsultarCorrequisitosActionPerformed
      ConsultarCorrequisitosCurso CCC = new ConsultarCorrequisitosCurso();
      CCC.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnIrConsultarCorrequisitosActionPerformed

    private void btnIrEliminarRequisitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrEliminarRequisitoActionPerformed
      EliminarRequisitoCurso ERC = new EliminarRequisitoCurso();
      ERC.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnIrEliminarRequisitoActionPerformed

    private void btnIrEliminarCursoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrEliminarCursoPlanActionPerformed
      EliminarCursoPlanEstudios ECPE = new EliminarCursoPlanEstudios();
      ECPE.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnIrEliminarCursoPlanActionPerformed

    private void btnIrEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrEliminarCursoActionPerformed
      EliminarCurso EC = new EliminarCurso();
      EC.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnIrEliminarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Conexion conexion = new Conexion();
                conexion.getConexion();
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrConsultarCorrequisitos;
    private javax.swing.JButton btnIrConsultarPlan;
    private javax.swing.JButton btnIrConsultarPlanConCurso;
    private javax.swing.JButton btnIrConsultarRequisitos;
    private javax.swing.JButton btnIrCrearPlan;
    private javax.swing.JButton btnIrEliminarCurso;
    private javax.swing.JButton btnIrEliminarCursoPlan;
    private javax.swing.JButton btnIrEliminarRequisito;
    private javax.swing.JButton btnIrRegistroCoYRequisitos;
    private javax.swing.JButton btnIrRegistroCurso;
    private javax.swing.JButton btnIrRegistroEscuela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
