/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import conexionBD.*;
import logicadenegocios.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Luis Aaron
 */
public class RegistroPlanEstudio extends javax.swing.JFrame {
  EscuelaOAreaAcademicaBD conexionEscuela = new EscuelaOAreaAcademicaBD();
  PlanDeEstudioBD conexionPlan = new PlanDeEstudioBD();
  EscuelaPlanEstudioBD conexionPlanEscuela = new EscuelaPlanEstudioBD();
  
    /**
     * Creates new form RegistroPlanEstudio
     */
    public RegistroPlanEstudio() {
        initComponents();
        cargarComboBoxEscuelas();
    }
    
    private void cargarComboBoxEscuelas(){
      ResultSet rs = conexionEscuela.consultarEscuelas();
      
      try{
        while(rs.next()){
          cbEscuelaPropietaria.addItem(rs.getString("IDEscuela") + " - " + 
                  rs.getString("Nombre"));
        }
      }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
      }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel6 = new javax.swing.JLabel();
    cbEscuelaPropietaria = new javax.swing.JComboBox<>();
    btnRegistrarPlanEstudios = new javax.swing.JButton();
    btnRegresar = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    tbCodigoPlan = new javax.swing.JTextField();
    tbVigenciaPlan = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel6.setText("Vigencia del plan de estudios: ");

    btnRegistrarPlanEstudios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnRegistrarPlanEstudios.setText("Registrar nuevo plan de estudios");
    btnRegistrarPlanEstudios.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegistrarPlanEstudiosActionPerformed(evt);
      }
    });

    btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnRegresar.setText("Regresar");
    btnRegresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegresarActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("REGISTRO DE PLANES DE ESTUDIO");

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setText("Escuela propietaria del curso: ");

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel4.setText("Código del plan de estudio: ");

    tbCodigoPlan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbCodigoPlanActionPerformed(evt);
      }
    });

    tbVigenciaPlan.setText("YYYY/MM/DD");
    tbVigenciaPlan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tbVigenciaPlanActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel6)
                  .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(tbCodigoPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                  .addComponent(tbVigenciaPlan))
                .addGap(33, 33, 33))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(cbEscuelaPropietaria, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(215, 215, 215)
            .addComponent(jLabel1)))
        .addGap(30, 30, 30))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel7)
            .addGap(123, 123, 123))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(btnRegistrarPlanEstudios)
            .addGap(101, 101, 101)
            .addComponent(btnRegresar)
            .addGap(30, 30, 30))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(31, 31, 31)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(cbEscuelaPropietaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(tbCodigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(41, 41, 41)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tbVigenciaPlan))
        .addGap(41, 41, 41)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnRegistrarPlanEstudios)
          .addComponent(btnRegresar))
        .addGap(26, 26, 26)
        .addComponent(jLabel7)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * 
   * @param evt 
   */
    private void tbCodigoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCodigoPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCodigoPlanActionPerformed

    /**
     * 
     * @param evt 
     */
    private void tbVigenciaPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbVigenciaPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbVigenciaPlanActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      Principal nPrincipal = new Principal();
      nPrincipal.setVisible(true);
      
      this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

  private boolean validarFecha(int ano, int mes, int dia) throws java.time.DateTimeException{
    try{
      LocalDate.of(ano, mes, dia);
      return true;
    }catch(java.time.DateTimeException e){
      return false;
    }
  }
    
  private void btnRegistrarPlanEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPlanEstudiosActionPerformed
    String infoEscuela = (String) cbEscuelaPropietaria.getSelectedItem();
    String codigoEscuela = infoEscuela.substring(0, infoEscuela.indexOf("-")-1);
    String nombreEscuela = infoEscuela.substring(infoEscuela.indexOf("-")+2, infoEscuela.length());
    EscuelaOAreaAcademica escuela = new EscuelaOAreaAcademica(nombreEscuela, codigoEscuela);
    String numPlan = tbCodigoPlan.getText();    
    String info = tbVigenciaPlan.getText();
    String ano = info.substring(0, info.indexOf("/"));
    int anos = Integer.parseInt((ano));
    String me = info.substring(info.indexOf("/")+1, info.indexOf("/")+3);
    int mes = Integer.parseInt((me));
    String dia = info.substring(info.indexOf("/")+4, info.length());
    int dias = Integer.parseInt((dia));
    if(validarFecha(anos, mes, dias)){
      JOptionPane.showMessageDialog(null, "La fecha ingresada no es válida. "
              + "Po favor vuelva a intentar ingresa la fecha.");
      return;
    }
    LocalDate fechaEntradaVigencia = LocalDate.of(anos, mes, dias);
    PlanDeEstudio plan = new PlanDeEstudio(escuela,numPlan,fechaEntradaVigencia);
    PlandeEscuela planEscuela = new PlandeEscuela(codigoEscuela, numPlan);
    
    if(conexionPlan.existePlanEstudio(plan)){
      JOptionPane.showMessageDialog(null, "Ya existe un plan con el código " +
              "ingresado. Por favor ingrese un código diferente.");
    }else{
      conexionPlan.insertarPlan(plan);
      conexionPlanEscuela.insertarEscuelaPlan(planEscuela);
    }
  }//GEN-LAST:event_btnRegistrarPlanEstudiosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistroPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistroPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistroPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistroPlanEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistroPlanEstudio().setVisible(true);
//            }
//        });
//    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnRegistrarPlanEstudios;
  private javax.swing.JButton btnRegresar;
  private javax.swing.JComboBox<String> cbEscuelaPropietaria;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JTextField tbCodigoPlan;
  private javax.swing.JTextField tbVigenciaPlan;
  // End of variables declaration//GEN-END:variables
}
